[package]
name = "m1fexplained"
version = "0.1"
lean_version = "leanprover-community/lean:3.46.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "f089486a9af40d019f9ecf7d86a055eb2801124b"}
